### ISSUE TITLE
return wrong 'id' property of resources of the same type

### ISSUE THREAD

**Issue by ttzeng** [01org/iot-rest-api-server#43] opened 2016-12-23 06:51 UTC
While registering multiple resources of the same type using [a parameterized script](https://github.com/ttzeng/node-examples/blob/master/iotivity-node/tools/binarySwitch.js), the discover `/res` indicates they have the same `di` value but different `href` property (ref the [attached report](https://github.com/01org/iot-rest-api-server/files/670369/res.txt)). However, when query the property of the resource through `href+di,` the server returns the wrong [id](**url**) property:

$ ./test/oic-get /a/led1?di=63393562-3338-3764-2d30-6134342d3438
192.168.1.104:8000 **/a/led1**?di=63393562-3338-3764-2d30-6134342d3438
{"properties":{"id":"**led1**","value":false}}
HTTP: 200

$ ./test/oic-get **/a/led0**?di=63393562-3338-3764-2d30-6134342d3438
192.168.1.104:8000 /a/led0?di=63393562-3338-3764-2d30-6134342d3438
{"properties":{"id":"**led1**","value":false}}
HTTP: 200

$ ./test/oic-get **/a/led2**?di=63393562-3338-3764-2d30-6134342d3438
192.168.1.104:8000 /a/led2?di=63393562-3338-3764-2d30-6134342d3438
{"properties":{"id":"**led1**","value":false}}
HTTP: 200

$ ./test/oic-get **/a/led3**?di=63393562-3338-3764-2d30-6134342d3438
192.168.1.104:8000 /a/led3?di=63393562-3338-3764-2d30-6134342d3438
{"properties":{"id":"**led1**","value":false}}
HTTP: 200

**Comment by nagineni** [comment] 2016-12-23 16:21
This seems to be an issue with iotivity or our node bindings.

**Comment by nagineni** [comment] 2017-01-09 09:18
The root cause of the issue is - having the same device ID for the resources that were registered in different processes using the same script(i.e led.js).

Device ID persistence mechanism creates and uses the same device ID if the same script has been started several times, so starting same script multiple times for registering different resources can be an issue since they all will contain the same device ID.

Try registering all the resources of same type in a single process using the same script (like led.js) or use different script name for each resource(like led1.js, led2.js...). If you want to avoid the code duplication, put the reusable code in a file (led.js) and require() that in other files.

**Comment by ttzeng** [comment] 2017-01-09 14:34
Does it mean we can't use traditional way to differentiate resources with command line parameters? It doesn't make sense, do we consider to change the device ID persistence mechanism?

**Comment by nagineni** [comment] 2017-01-10 15:22
+ @zolkis @gabrielschulhof

> Does it mean we can't use traditional way to differentiate resources with command line parameters?

True, with the current mechanism you can't make it to work by starting the same script and instantiating iotivity-node muplti times one the same device. You can give a try by changing the  script to instantiate iotivity-node only once even if you start it multiple times with different resource name as command line option.

> It doesn't make sense, do we consider to change the device ID persistence mechanism?

We will definitely revisit this device ID persistence mechanism when we have secure and provisioning functionality fully working in iotivity stack. For now, we have different options to solve the issue, so we can survive with it I hope.

**Comment by zolkis** [comment] 2017-01-10 16:37
By definition, an OCF device (server in this case) is defined by the instance of the OCF stack, and that includes network namespace, process namespace etc.

So one should not start multiple servers from command line with the same scripts, if it does not also guarantee a separate network address (or address:port that is maintained by the stack, i.e. iotivity), and a different managed set of physical HW sensors/actuators. Doing so currently can be considered as an error of the server application developer.

With every OCF stack instance the provisioning process is run separately, so they will get different device id's, mapped to different network addresses. Those device id's are persistent over reboots, but the same context (network namespace and managed resources) needs to be maintained by the local configuration of the device.

Therefore I think this issue comes from invalid usage, i.e. looks like the bug is invalid. 

Maybe I misunderstand: please state what is the expected behavior in this use case.

**Comment by ttzeng** [comment] 2017-01-11 05:04
@zolkis Would you please clarify where is the definition? I think OCF specs define how the Device Identity should comply regardless the implementation. In the OIC Security spec 1.1, section 7.1:

"OIC devices SHALL identified by a DeviceID value... **Device IDs shall be unique within the scope of operation of the corresponding OIC network**, and should be universally unique."

It's normal practice to keep software programs generic and move the dynamic parts as parameters such as the command line arguments, it's definitely not an error of the application!  Instead, it might not be a good design of the implementation to use the script namespace in composing the DeviceID, which provent developers to start multiple homogeneous servers using a generic script.

Let's take a look on how the client connect to the server.  You could see from below screenshot
![screenshot](https://cloud.githubusercontent.com/assets/1763431/21836129/a2ab8582-d7fd-11e6-8456-c4160abe7156.png) that every servers, no matter they are hosted by different scripts or multiple instances of a generic script, all have dedicated ports, so they are different OIC devices, they should have different DeviceID according the spec, but we get the DeviceID for those cloned devices.

**Comment by zolkis** [comment] 2017-01-11 06:04
The point was you did not have separate devices in the example, so no wonder you didn't get separate device id's. You can't provision separate device id's when you just launch different processes running the same stack with the same network address. The whole use case you have presented is invalid.

**Comment by ttzeng** [comment] 2017-01-11 06:29
Are you saying separate platforms? I am referring logical OIC devices. From above screenshot, they are assigned same IP address but different ports, shouldn't we treat them as different devices each has his own unique ID?

**Comment by zolkis** [comment] 2017-01-11 08:31
Platform is the HW. Device is the SW stack instance + network namespace.
Same IP and different ports should be OK for separate devices. 
In the examples above the port numbers are the same.

**Comment by ttzeng** [comment] 2017-01-11 10:07
In the above example, the network port used for each server is different (led0: 38987, led1: 56914, led2: 39875, led3: 35226), even these servers are launched from the same script. Should they be assigned to different DeviceIDs?

**Comment by zolkis** [comment] 2017-01-11 11:33
In principle in an OCF network you should be able to GET resources by just the URI, which can contain device id OR IP:port for authority, but not both. In the example above you seem to use `192.168.1.104:8000`, at least that device is providing responses.
Could you share the the full test setup script? How do you start the devices, how do you register resources, etc? Your link to binarySwitch.js doesn't describe how you are using it.

**Comment by poussa** [comment] 2017-01-11 12:18
@ttzeng can you stop launching the resources from the same script using the cmd line, if you are still doing that. It is a known limitation in our bindings and as stated we'll look into it later.

Can we have your script code?

**Comment by gabrielschulhof** [comment] 2017-01-11 18:02
@ttzeng
> It's normal practice to keep software programs generic and move the dynamic parts as parameters such as the command line arguments, it's definitely not an error of the application!

```JS
// ./server.js:
// Common code in a common place
module.exports = function( resourceInit, handlers ) {
  require( "iotivity-node" ).server.register( resourceInit )
    .then( function( resource ) {
      var index;

      for ( index in handlers ) {
        resource[ index ]( handlers[ index ] );
      }
    } )
    .catch( function( error ) {
      console.error( error.stack + "\n" + JSON.stringify( error, null, 4 ) );
      process.exit( 1 );
    } );
};
```
```JS
// led1.js:
// Sensor-instance-specific code in its own file
require( "./server" )( {
  resourcePath: "/a/led1",
  resourceTypes: [ "core.light" ],
  interfaces: [ "oic.if.baseline" ],
  discoverable: true,
  observable: true
}, {
  onretrieve: function( request ) {

    // Report status or whatever
    request.respond();
  },
  onupdate: function( request ) {

    // Turn light on or off and then respond
    request.respond();
  }
} );
```
```JS
// fan1.js
// Sensor-instance-specific code in its own file
require( "./server" )( {
  resourcePath: "/a/fan1",
  resourceTypes: [ "core.fan" ],
  interfaces: [ "oic.if.baseline" ],
  discoverable: true,
  observable: true
}, {
  onretrieve: function( request ) {

    // Report status or whatever
    request.respond();
  },

  onupdate: function( request ) {

    // Turn fan on or off and then respond
    request.respond();
  }
} );
```
```JS
// launcher.js
// The launcher to tie it all together
var paths = {
  "/a/fan1": "./fan1",
  "/a/led1": "./led1"
};

var desiredScript = paths[ process.argv[ 2 ] ];

if ( !desiredScript ) {
  console.error( process.argv[ 2 ] + " not recognized!" );
  process.exit( 1 );
}

require( "child_process" ).spawn( "node", [ desiredScript ] );
```
Now, you can
```bash
$ node ./launcher.js /a/led1 &
$ node ./launcher.js /a/fan1 &
```
and you'll have two copies of the stack launched from two different files on two different ports with two different device IDs from a single, shared launcher script.

**Comment by poussa** [comment] 2017-06-21 07:12
I think we can close this issue since it was not an issue in iot-rest-api-server to start with.

@nagineni @ttzeng

**Comment by nagineni** [comment] 2017-06-21 07:27
Yes,  it's not a rest server issues. The expected behavior can be achieved by making changes in the servers.

**Closed by nagineni** 2017-06-21 07:27 UTC
