### ISSUE TITLE
REST API server reports multiple entries for same device?

### ISSUE THREAD

**Issue by ttzeng** [01org/iot-rest-api-server#41] opened 2016-11-17 07:40 UTC
Hi,

In some cases, the REST API server will reports multiple entries in the JSON resource array like below (detailed in the attached):

{"di":"61363166-3530-3066-2d35-3062382d3436","links":[{"href":"/oic/sec/doxm","rt":"oic.r.doxm","if":"oic.if.baseline"}]},{"di":"61363166-3530-3066-2d35-3062382d3436","links":[{"href":"/oic/sec/doxm","rt":"oic.r.doxm","if":"oic.if.baseline"}]},{"di":"61363166-3530-3066-2d35-3062382d3436","links":[{"href":"/oic/sec/pstat","rt":"oic.r.pstat","if":"oic.if.baseline"}]},{"di":"61363166-3530-3066-2d35-3062382d3436","links":[{"href":"/oic/sec/pstat","rt":"oic.r.pstat","if":"oic.if.baseline"}]},{"di":"61363166-3530-3066-2d35-3062382d3436","links":[{"href":"/oic/d","rt":"oic.wk.d","if":"oic.if.baseline"}]},{"di":"61363166-3530-3066-2d35-3062382d3436","links":[{"href":"/oic/d","rt":"oic.wk.d","if":"oic.if.baseline"}]},{"di":"61363166-3530-3066-2d35-3062382d3436","links":[{"href":"/oic/p","rt":"oic.wk.p","if":"oic.if.baseline"}]},{"di":"61363166-3530-3066-2d35-3062382d3436","links":[{"href":"/oic/p","rt":"oic.wk.p","if":"oic.if.baseline"}]},{"di":"61363166-3530-3066-2d35-3062382d3436","links":[{"href":"/a/gas","rt":"oic.r.sensor.carbondioxide","if":"oic.if.baseline"}]},{"di":"61363166-3530-3066-2d35-3062382d3436","links":[{"href":"/a/gas","rt":"oic.r.sensor.carbondioxide","if":"oic.if.baseline"}]},{"di":"65623462-3236-3361-2d30-3038332d3462","links":[{"href":"/oic/sec/doxm","rt":"oic.r.doxm","if":"oic.if.baseline"}]},{"di":"65623462-3236-3361-2d30-3038332d3462","links":[{"href":"/oic/sec/doxm","rt":"oic.r.doxm","if":"oic.if.baseline"}]},{"di":"65623462-3236-3361-2d30-3038332d3462","links":[{"href":"/oic/sec/pstat","rt":"oic.r.pstat","if":"oic.if.baseline"}]},{"di":"65623462-3236-3361-2d30-3038332d3462","links":[{"href":"/oic/sec/pstat","rt":"oic.r.pstat","if":"oic.if.baseline"}]},{"di":"65623462-3236-3361-2d30-3038332d3462","links":[{"href":"/oic/d","rt":"oic.wk.d","if":"oic.if.baseline"}]},{"di":"65623462-3236-3361-2d30-3038332d3462","links":[{"href":"/oic/d","rt":"oic.wk.d","if":"oic.if.baseline"}]},{"di":"65623462-3236-3361-2d30-3038332d3462","links":[{"href":"/oic/p","rt":"oic.wk.p","if":"oic.if.baseline"}]},{"di":"65623462-3236-3361-2d30-3038332d3462","links":[{"href":"/oic/p","rt":"oic.wk.p","if":"oic.if.baseline"}]},{"di":"65623462-3236-3361-2d30-3038332d3462","links":[{"href":"**/a/illuminance**","rt":"oic.r.sensor.illuminance","if":"oic.if.baseline"}]},{"di":"65623462-3236-3361-2d30-3038332d3462","links":[{"href":"**/a/illuminance**","rt":"oic.r.sensor.illuminance","if":"oic.if.baseline"}]},{"di":"62313332-3936-6134-2d37-6639622d3430","links":[{"href":"/oic/sec/doxm","rt":"oic.r.doxm","if":"oic.if.baseline"}]},{"di":"62313332-3936-6134-2d37-6639622d3430","links":[{"href":"/oic/sec/doxm","rt":"oic.r.doxm","if":"oic.if.baseline"}]},

**Comment by ttzeng** [comment] 2016-11-17 07:41
[res.txt](https://github.com/01org/iot-rest-api-server/files/596783/res.txt)

**Comment by poussa** [comment] 2016-11-17 07:42
Do you have multiple network interfaces? If so, that is the root cause. The latest iotivity-node has a fix for that. We need to update this project to use that version.

**Comment by ttzeng** [comment] 2016-11-17 07:45
Does that include loopback interface 'lo'? the device that the REST API server is running only has 'wlan0' and 'lo' interfaces.

**Comment by nagineni** [comment] 2016-12-09 08:25
I've not seen resource appearing on the loopback interface. I will investigate this issue.

**Comment by nagineni** [comment] 2017-01-24 07:57
This issue is reproducible always when client does the discovery repeatedly. I will add a fix for the issue soon.

**Comment by nagineni** [comment] 2017-01-27 09:09
Fixed in https://github.com/01org/iot-rest-api-server/pull/44

**Closed by nagineni** 2017-01-27 09:09 UTC
